spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  datasource:
    url: jdbc:h2:tcp://localhost/~/portfolio-server-h2-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization : true
logging.level:
  org.hibernate.SQL: debug